### ISSUE TITLE
extract_ranef() fails for random slopes on factor predictors

### ISSUE THREAD

**Issue by derekpowell** [m-clark/gammit#1] opened 2020-06-17 21:23 UTC
The `extract_ranef()` function fails for models with random slopes for factor variables, lme4 syntax (1 + factor1|factor2).

Here's a minimal example:

```
library(mgcv)
library(lme4)
library(dplyr)

data(sleepstudy)

ga_model <- gam(Reaction ~ Days + s(Subject, bs = "re") + s(Days, Subject, bs = "re"),
                data = sleepstudy %>% 
                    mutate(Days = as.factor(Days))

)

extract_ranef(ga_model)
```

Running this code produces the error: `Error: Column `group` must be length 198 (the number of rows) or one, not 36`.

P.S. Really love your blog posts and all the work you've done here and elsewhere to make mixed effect modeling practical for large datasets!

**Comment by m-clark** [comment] 2020-06-18 20:04
Hi @derekpowell, thanks for posting and the kind words!  A couple things-

If I try your code as is, I get the following:

``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-31. For overview type 'help("mgcv-package")'.
library(lme4)
#> Loading required package: Matrix
#> 
#> Attaching package: 'lme4'
#> The following object is masked from 'package:nlme':
#> 
#>     lmList
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following object is masked from 'package:nlme':
#> 
#>     collapse
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

data(sleepstudy)

ga_model <- gam(Reaction ~ Days + s(Subject, bs = "re") + s(Days, Subject, bs = "re"),
                data = sleepstudy %>% 
                  mutate(Days = as.factor(Days))
                
)
#> Error in gam(Reaction ~ Days + s(Subject, bs = "re") + s(Days, Subject, : Model has more coefficients than data
```

<sup>Created on 2020-06-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I get the same thing with lme4.  If you leave `Days` as numeric, it works as intended, but there could be something else going on with the function causing some error. I would just need a model I could check.

More to the point, and I need to update the readme to reflect this, my [mixedup package](https://github.com/m-clark/mixedup) has all the mixed model specific functionality from here and more, so you might want to use that instead.  I think this package has become mostly deprecated as a result.  I'm about to push an update to mixedup today or tomorrow.

**Comment by derekpowell** [comment] 2020-06-18 23:15
Thanks for the speedy reply! Seems I made a mistake in my minimal example as I got the same result as you when I ran it again. So I fixed it up and here's another try with the `mixedup` package producing a similar error:

```
library(mgcv)
library(mixedup)
library(lme4)
library(dplyr)

data(sleepstudy)

ga_model <- gam(Reaction ~ Days + s(Subject, bs = "re") + s(Days, Subject, bs = "re"),
                data = sleepstudy %>% 
                    mutate(Days = factor(case_when(
                        Days < 2 ~ "x",
                        Days < 5 ~ "y",
                        TRUE ~ "z"
                    )))
                
)

extract_random_coefs(ga_model)
```

**Comment by m-clark** [comment] 2020-06-20 13:43
I see the issue seems to be with dealing with the factor which I hadn't considered for a gam.  I'll have to put some thought into how to deal with that, as mgcv doesn't distinguish the factor level names for the coefficients in a meaningful way.

**Comment by m-clark** [comment] 2020-06-24 13:25
@derekpowell I'm closing this for now as I've updated the readme here posing this as a superseded package (possibly to be returned to later).  See more details at the [mixedup issue](https://github.com/m-clark/mixedup/issues/12), where I've added the fix and it passes for this particular problem.

**Closed as completed by m-clark** 2020-06-24 13:25 UTC
